name: GitHub Check Exercise 1
on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - 'assignments/2-programming/**'

jobs:
  Test-Execution:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Was triggered by a ${{ github.event_name }} by ${{ github.actor }}"
      - run: echo "DEBUG! Looking how a pull request event looks ${{ toJSON(github.event) }}"
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          cd assignments/2-programming && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          # cd assignments/2-programming && flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          cd assignments/2-programming && pytest .
      - name: Write Message to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.